# Generated by Django 4.1.4 on 2022-12-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyrecord',
            options={'verbose_name_plural': 'PolicyRecords'},
        ),
    ]
