# Generated by Django 4.1.4 on 2022-12-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
