# Generated by Django 4.1.4 on 2022-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_policy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='policy',
            field=models.ManyToManyField(to='main.policy'),
        ),
    ]
