# Generated by Django 4.1.4 on 2022-12-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='policy',
            new_name='poli',
        ),
    ]
