# Generated by Django 4.1.4 on 2022-12-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_policy_customer_poli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='poli',
            new_name='policy',
        ),
    ]
